<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROYsQrt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROYsQrt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROYsQrt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROYsQrt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerROYsQrt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ROYsQrt',
    'container.build_id' => '504054df',
    'container.build_time' => 1655627537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROYsQrt');
